export interface Pila {
    pilaId: number,
    posicionPila?: number,
    codigoPila?: string,
    nombrePila?: string,
    cantidadPanos?: number,
    anchoPila?: number,
    largoPila?: number,
    descripcionPila?: string,
    ubicacionPila?: string,
    latLongPila?: string,
    clienteId?: number, 
    createDate?: Date,
    active: boolean,
}